import { VeterinaryService, PetProduct, Appointment, Order, MedicalRecordFile } from './types';

export const VETERINARY_SERVICES: VeterinaryService[] = [
  {
    id: 'urgencias-247',
    name: 'Urgencias & Unidad de Cuidados Intensivos (UCI) 24/7',
    category: 'Urgencias 24/7',
    shortDescription: 'Atención crítica de triage inmediato con monitoreo multiparámetro, oxigenoterapia y quirófano de emergencia activo día y noche.',
    fullDescription: 'Unidad de choque con ventilación mecánica, soporte hemodinámico avanzado, bombas de infusión y disponibilidad inmediata de hemoderivados para pacientes con politraumatismos, intoxicaciones o fallas orgánicas agudas.',
    priceEstimate: 140000,
    duration: 'Inmediata (Sin cita)',
    badge: 'Atención 24 Horas',
    doctorInCharge: 'Dr. Camilo Arboleda, MVZ',
    doctorSpecialty: 'Diplomado en Cuidados Críticos & Urgencias',
    iconName: 'AlertCircle',
    available247: true,
    image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'consulta-especializada',
    name: 'Consulta Médica General & Especialidades',
    category: 'Consulta Médica Especializada',
    shortDescription: 'Evaluación integral clínica: Cardiología, Dermatología, Endocrinología, Gastroenterología y Medicina Felina Friendly.',
    fullDescription: 'Consulta exhaustiva de 45 minutos con anamnesis clínica detallada, examen físico sistemático, medición de presión arterial veterinaria y plan terapéutico individualizado.',
    priceEstimate: 95000,
    duration: '45 minutos',
    badge: 'Popular',
    doctorInCharge: 'Dra. Valentina Restrepo, MV',
    doctorSpecialty: 'Especialista en Medicina Interna y Felina',
    iconName: 'Stethoscope',
    available247: false,
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cirugia-alta-complejidad',
    name: 'Cirugía de Alta Complejidad & Traumatología',
    category: 'Cirugía de Alta Complejidad',
    shortDescription: 'Quirófano estéril con monitoreo anestésico inhalatorio (Sevoflurano), osteosíntesis ortopédica y cirugía laparoscópica mínimamente invasiva.',
    fullDescription: 'Procedimientos quirúrgicos con tecnología de sellado vascular ultrasónico, control estricto de temperatura corporal y recuperación postquirúrgica monitorizada por enfermería especializada.',
    priceEstimate: 420000,
    duration: '1 a 3 horas',
    badge: 'Quirófano Certificado',
    doctorInCharge: 'Dr. Mateo Sánchez, MVZ Esp.',
    doctorSpecialty: 'Cirujano Ortopedista y Neurocirugía Veterinaria',
    iconName: 'Activity',
    available247: true,
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'diagnostico-laboratorio',
    name: 'Laboratorio Clínico & Imagenología Digital In-House',
    category: 'Diagnóstico & UCI',
    shortDescription: 'Ecografía Doppler de alta resolución, Rayos X digital directo y hemograma automatizado con resultados en 20 minutos.',
    fullDescription: 'Equipamiento IDEXX de última generación para química sanguínea instantánea, gases arteriales, electrolitos, citologías inmediatas y biopsias guiadas por ultrasonido.',
    priceEstimate: 110000,
    duration: '30 minutos',
    badge: 'Resultados 20 min',
    doctorInCharge: 'Dra. Sofía Londoño, MV',
    doctorSpecialty: 'Radiología y Patología Clínica',
    iconName: 'Microscope',
    available247: true,
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'vacunacion-inmunologia',
    name: 'Vacunación Preventiva & Certificación Internacional',
    category: 'Vacunación & Desparasitación',
    shortDescription: 'Biológicos de cadena de frío certificada, desparasitación interna/externa con peso exacto y microchip ISO para viajes.',
    fullDescription: 'Planes preventivos adaptados al estilo de vida del paciente (canino, felino, hurones, conejos) con cartilla sanitaria digital y recordatorios automáticos de refuerzo.',
    priceEstimate: 75000,
    duration: '30 minutos',
    badge: 'Esquema Certificado',
    doctorInCharge: 'Dr. Andrés Peña, MV',
    doctorSpecialty: 'Medicina Preventiva e Inmunología',
    iconName: 'ShieldCheck',
    available247: false,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'grooming-spa-dermato',
    name: 'Grooming Médico & Spa Dermatológico Asistido',
    category: 'Grooming & Spa Dermatológico',
    shortDescription: 'Baños de ozono, tratamientos para dermatitis atópica, corte de raza higiénico libre de estrés con cosmética botánica.',
    fullDescription: 'Área de estética veterinaria con personal capacitado en manejo "Fear Free". Uso exclusivo de toallas desinfectadas, secado silencioso a baja temperatura y aromaterapia relajante.',
    priceEstimate: 68000,
    duration: '1 hora 30 min',
    badge: 'Manejo Fear-Free',
    doctorInCharge: 'Dra. Laura Morales, MVZ',
    doctorSpecialty: 'Dermatología Veterinaria y Cosmetología Clínica',
    iconName: 'Sparkles',
    available247: false,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=800&q=80',
  },
];

export const PET_PRODUCTS: PetProduct[] = [
  {
    id: 'prod-1',
    name: 'Royal Canin Veterinary Diet Gastrointestinal Canine 10kg',
    brand: 'Royal Canin Vets',
    category: 'alimento',
    petType: 'perro',
    price: 345000,
    originalPrice: 380000,
    stock: 14,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=800&q=80',
    badge: 'Fórmula Clínica',
    description: 'Dieta veterinaria de alta digestibilidad enriquecida con fibras prebióticas (FOS y MOS) y EPA/DHA para recuperación gastrointestinal.',
    isGourmet: true,
    formulaVeterinaria: true,
    rating: 4.9,
    reviewsCount: 88,
  },
  {
    id: 'prod-2',
    name: 'Hill\'s Prescription Diet k/d Feline Renal Health Pouch Mousse 85g',
    brand: 'Hill\'s Science Diet',
    category: 'alimento',
    petType: 'gato',
    price: 18500,
    originalPrice: 21000,
    stock: 42,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80',
    badge: 'Soporte Renal',
    description: 'Nutrición clínica clínicamente probada para mejorar la calidad y expectativa de vida en gatos con insuficiencia renal crónica.',
    isGourmet: true,
    formulaVeterinaria: true,
    rating: 4.8,
    reviewsCount: 114,
  },
  {
    id: 'prod-3',
    name: 'Snacks Gourmet Lomo de Salmón Noruego Deshidratado 120g',
    brand: 'Pet Gourmet Artisan',
    category: 'snacks',
    petType: 'todos',
    price: 38000,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=800&q=80',
    badge: '100% Natural',
    description: 'Mono-proteína pura sin conservantes, sal añadida ni granos. Rico en ácidos grasos Omega-3 y Omega-6 para pelaje brillante.',
    isGourmet: true,
    formulaVeterinaria: false,
    rating: 5.0,
    reviewsCount: 63,
  },
  {
    id: 'prod-4',
    name: 'Bravecto Comprimido Masticable Perros (10 - 20 kg)',
    brand: 'MSD Salud Animal',
    category: 'farmacia',
    petType: 'perro',
    price: 162000,
    originalPrice: 175000,
    stock: 19,
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
    badge: '12 Semanas Protección',
    description: 'Protección oral continua contra pulgas y garrapatas durante 12 semanas completas. Eficacia sistémica inmediata.',
    isGourmet: false,
    formulaVeterinaria: true,
    rating: 4.9,
    reviewsCount: 230,
  },
  {
    id: 'prod-5',
    name: 'Cosequin Maximum Strength Plus MSM Condroprotector 60 Tabs',
    brand: 'Nutramax Labs',
    category: 'farmacia',
    petType: 'perro',
    price: 189000,
    stock: 8,
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=800&q=80',
    badge: 'Últimas 8 uds',
    description: 'Fórmula veterinaria número 1 recomendada con Glucosamina HCl, Sulfato de Condroitina de bajo peso molecular y MSM articular.',
    isGourmet: false,
    formulaVeterinaria: true,
    rating: 4.9,
    reviewsCount: 97,
  },
  {
    id: 'prod-6',
    name: 'Oxbow Critical Care Alimento Asistido Herbívoros 141g',
    brand: 'Oxbow Animal Health',
    category: 'alimento',
    petType: 'exotico',
    price: 79000,
    stock: 11,
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80',
    badge: 'Especial Mascotas Exóticas',
    description: 'Fórmula de recuperación de heno Timothy premium con alto contenido de fibra para conejos, cobayos y reptiles herbívoros.',
    isGourmet: true,
    formulaVeterinaria: true,
    rating: 4.8,
    reviewsCount: 34,
  },
  {
    id: 'prod-7',
    name: 'Arnés Anatómico Pro-Orthopedic No-Pull Reflectivo',
    brand: 'Kindev Pet Gear',
    category: 'accesorios',
    petType: 'perro',
    price: 125000,
    stock: 16,
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80',
    badge: 'Diseño Ergonómico',
    description: 'Distribuye la presión de tiro sobre el tórax sin estrangular la tráquea ni limitar la amplitud del movimiento escapular.',
    isGourmet: false,
    formulaVeterinaria: false,
    rating: 4.7,
    reviewsCount: 45,
  },
  {
    id: 'prod-8',
    name: 'Purina Pro Plan Veterinary Diets FortiFlora Feline 30 Sobres',
    brand: 'Purina Vets',
    category: 'farmacia',
    petType: 'gato',
    price: 135000,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    badge: 'Probiótico Clínico',
    description: 'Suplemento probiótico con Enterococcus faecium microencapsulado para restaurar el equilibrio microbiótico intestinal.',
    isGourmet: true,
    formulaVeterinaria: true,
    rating: 5.0,
    reviewsCount: 156,
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-001',
    code: 'VC-8921',
    petName: 'Lucas',
    petType: 'perro',
    petBreed: 'Golden Retriever',
    petAge: '4 años',
    petWeight: '32 kg',
    specialty: 'Cirugía & Traumatología',
    doctorName: 'Dr. Mateo Sánchez, MVZ Esp.',
    date: '2026-09-14',
    timeSlot: '10:00 AM',
    tutorName: 'Mariana Gómez',
    tutorPhone: '+57 312 456 7890',
    tutorEmail: 'mariana.gomez@gmail.com',
    reason: 'Claudicación en extremidad posterior derecha tras salto en parque.',
    isEmergency: false,
    requiresPetTaxi: false,
    status: 'Confirmada',
    createdAt: '2026-09-12 08:30',
  },
  {
    id: 'apt-002',
    code: 'VC-8922',
    petName: 'Mía',
    petType: 'gato',
    petBreed: 'Siamés',
    petAge: '7 años',
    petWeight: '3.8 kg',
    specialty: 'Consulta Medicina Felina & Nefrología',
    doctorName: 'Dra. Valentina Restrepo, MV',
    date: '2026-09-13',
    timeSlot: '02:30 PM',
    tutorName: 'Carlos Eduardo Peña',
    tutorPhone: '+57 300 891 2233',
    tutorEmail: 'carlos.pena@outlook.com',
    reason: 'Control semestral de función renal y ecografía de control.',
    isEmergency: false,
    requiresPetTaxi: true,
    status: 'Pendiente',
    createdAt: '2026-09-12 09:15',
  },
  {
    id: 'apt-003',
    code: 'VC-8923',
    petName: 'Rocky',
    petType: 'perro',
    petBreed: 'Bulldog Francés',
    petAge: '2 años',
    petWeight: '12.5 kg',
    specialty: 'Urgencias & Cuidados Críticos 24/7',
    doctorName: 'Dr. Camilo Arboleda, MVZ',
    date: '2026-09-12',
    timeSlot: 'Urgencia Inmediata',
    tutorName: 'Daniela Salazar',
    tutorPhone: '+57 318 674 1109',
    tutorEmail: 'daniela.salazar@live.com',
    reason: 'Dificultad respiratoria aguda por golpe de calor en paseo diurno.',
    isEmergency: true,
    requiresPetTaxi: false,
    status: 'En Atención',
    createdAt: '2026-09-12 09:35',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    code: 'ORD-7741',
    customerName: 'Santiago Vélez',
    customerPhone: '+57 315 789 4432',
    customerAddress: 'Calle 10A # 36-22, El Poblado, Medellín',
    items: [
      { product: PET_PRODUCTS[0], quantity: 1 },
      { product: PET_PRODUCTS[2], quantity: 2 },
    ],
    subtotal: 421000,
    deliveryFee: 0,
    total: 421000,
    paymentMethod: 'WhatsApp Checkout',
    status: 'Preparando',
    createdAt: '2026-09-12 07:50',
  },
  {
    id: 'ord-102',
    code: 'ORD-7742',
    customerName: 'Andrea Montoya',
    customerPhone: '+57 311 902 3344',
    customerAddress: 'Carrera 43A # 18 Sur-120, Envigado',
    items: [
      { product: PET_PRODUCTS[3], quantity: 1 },
      { product: PET_PRODUCTS[1], quantity: 4 },
    ],
    subtotal: 236000,
    deliveryFee: 0,
    total: 236000,
    paymentMethod: 'Tarjeta en Clínica',
    status: 'Enviado',
    createdAt: '2026-09-11 16:20',
  },
];

export const INITIAL_MEDICAL_FILES: MedicalRecordFile[] = [
  {
    id: 'file-01',
    petName: 'Lucas (Golden Retriever)',
    tutorName: 'Mariana Gómez',
    documentType: 'Radiografía',
    fileName: 'RX_Lucas_Rodilla_Derecha_Lateral_AP.png',
    fileSize: '3.4 MB',
    fileUrl: 'https://picsum.photos/seed/rxvetdog/800/800',
    bucket: 'vetcare-clinical-records',
    rlsPolicy: 'auth.uid() = medical_staff_or_owner',
    notes: 'Sospecha de rotura de ligamento cruzado craneal. Confirmada articulación femorotibial con desplazamiento craneal leve.',
    uploadedAt: '2026-09-12 08:45',
  },
  {
    id: 'file-02',
    petName: 'Mía (Siamés)',
    tutorName: 'Carlos Eduardo Peña',
    documentType: 'Ecografía',
    fileName: 'Ecografia_Abdominal_Doppler_Mia.png',
    fileSize: '5.1 MB',
    fileUrl: 'https://picsum.photos/seed/ecocatvet/800/800',
    bucket: 'vetcare-clinical-records',
    rlsPolicy: 'auth.uid() = medical_staff_or_owner',
    notes: 'Parénquima renal conservado con relación corticomedular normal. Sin signos de hidronefrosis ni cálculos vesicales.',
    uploadedAt: '2026-09-11 14:10',
  },
  {
    id: 'file-03',
    petName: 'Rocky (Bulldog Francés)',
    tutorName: 'Daniela Salazar',
    documentType: 'Cuadro Hemático',
    fileName: 'Hemograma_Gases_Rocky_UCI.pdf',
    fileSize: '1.2 MB',
    fileUrl: 'https://picsum.photos/seed/labreportvet/800/800',
    bucket: 'vetcare-clinical-records',
    rlsPolicy: 'auth.uid() = medical_staff_or_owner',
    notes: 'Hematocrito 48%, lactato sanguíneo 2.4 mmol/L en descenso tras fluidoterapia fría e hiperoxia.',
    uploadedAt: '2026-09-12 09:40',
  },
];
